# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='permission_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('parentid', models.IntegerField()),
                ('level', models.IntegerField()),
                ('icon', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('visible', models.IntegerField(default=1)),
                ('url', models.CharField(max_length=255)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('view_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='role_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('zh_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(default='basicFramework', max_length=255, unique=True)),
                ('remember_token', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='role_user',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorities.roles'),
        ),
        migrations.AddField(
            model_name='role_user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorities.users'),
        ),
        migrations.AddField(
            model_name='permission_role',
            name='permission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorities.permissions'),
        ),
        migrations.AddField(
            model_name='permission_role',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorities.roles'),
        ),
    ]
