# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissions',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
